### ISSUE TITLE
POI attributes

### ISSUE THREAD

**Issue by fischerfscom** [opengeospatial/poi#100]
Are the following attribute possible with current data model or require data model extension:
- Scenic viewpoint: indicate scenic viewpoints (e.g. Grand Canyon) that tourists may visit
- Indicate upcoming events (e.g. football match) together with some relevant info (e.g. starting-time, teams)
- Real-time updates on wait times, crowds, and other important information as POI info (e.g. for an event, touristic area).  
- Weather forecast for a specific place/area (e.g. sunny weekend coming, expected heavy winds in an hour)

**Comment by cmheazel** [comment]
I think the re-design takes care of this.  Recommend to close.

**Comment by geofizzydrink** [comment]
Issue closed
