### ISSUE TITLE
What should be in the schema link?

### ISSUE THREAD

**Issue by howardtrickey** [opengeospatial/poi#106]
The recent update to the standard now has a "payload" and also a link that is supposed to describe the schema.  The question is: should the schema describe just the payload items, or the entire POI?

Both choices have their advantages:

Advantage of describing the whole POI:
- If the schema describes the whole POI, then one could imagine an implementation that reads the entire POI's schema, and then uses that to drive the parsing and understanding of the entire POI file / database.  If this is the implementation method, then having a schema that describes the whole POI would be easier for the implementer.

Advantage of describing just the payload:
- If the scheme describes just the payload, then one could imagine an implementation that knows the general POI schema and is hardwired to parse that (this may actually be easier than doing the parsing in an interpret-the-schema way), and then only has to do something runtime-schema-specific for the payload part (maybe even just checking for the absence/presence of certain well-known payload elements as a possible subset-understanding of the file).  Also, a shorter schema maybe be easier to peruse and understand for human readers.

If we go with the choice of just describing the payload, we need to furthermore be precise about what that means: for instance, it could mean that the schema describes an array of objects (probably property/value pairs), each of which can be any of a number of types. Or it could describe a choice of any number of object types, with the implication that there can be an arbitrary collection of those.  Or it could describe a single object which in turn is probably some kind of aggregate type, but leaving it up to the schema writer what kind of aggregate type it is.  The last choice probably offers the most control to the schema writer, so I would lean towards that.

**Comment by cmheazel** [comment]
The July 19 update should help clarify this issue.

**Comment by cmheazel** [comment]
July 19 added a PayloadSchema object which is associated with the POI_Payload.   PayloadSchema is defined as a representation of a syntactic model for a POI payload.

Recommend to close.
