### ISSUE TITLE
Collaboration on POI with ISO/TC211 as possible joint project...

### ISSUE THREAD

**Issue by rplews** [opengeospatial/poi#32]
There was a discussion at the ISO/TC211 WG10 meeting in Berlin (June 2, 2014) regarding OGC's POI project. Topics included the importance of the POI concept/construct to the LBS/UPA markets, how concepts of the POI are related to places not only to points, and that some of the currently proposed ideas in the POI design are similar to ISO 19155's (Place Identifier Architecture). Discussion continued in WG10 and later with members of the JAG on the idea of collaboration between the two groups, with an end-goal of the POI work becoming an IS, possibly as an extension of ISO 19155:2012.  I would be interested in continuing this discussion if the members of the POI SWG believe there is merit for any of these ideas. 

Reese Plews
ISO 19155 Editor
TC211 WG10 & OGC member
Japan

**Comment by anthonyarchie** [comment]
start from the beginning and leeks reconstruct the IOS
