### ISSUE TITLE
Is there a need for crowd sourced PoI (what are the benefits and challenges)?

### ISSUE THREAD

**Issue by EfarBen** [opengeospatial/poi#42]
Should consideration be given to crowd-sourced (volunteered geographic information) PoI? 
Noting that this may reduce the confidence in authoritative data unless appropriate confidence flags are associated with individual records and or approved/ acknowledged by an authoritative source.

**Comment by timoruohomaki** [comment]
Yes there is, but this is also a matter of data governance in general. As an example, crowd sourcing could be a part of a curated service that can also include recommendations and ratings from the crowd. So trying not to be too restrictive and consider different types of service offerings

**Comment by cperey** [comment]
Yes, if your feature of interest is crowdsourced, that information can be imported and captured as an attribute of the feature of interest but not part of the model. 

Provenance could be a property of the feature included in the Meta data. Not part of the model. 
It's an attribute of the feature that populates the PoI.
