### ISSUE TITLE
PoI SWG Telecon Minutes

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#43]
<div id="Minutes-2021-11-18">

### Participants
Matthew Purss
Koen De Baets
Holli Howard
Chuck Haezel

Meeting Started 23:15 AEST 

## Agenda
Draft Agenda:
1. Open/logistics
2. Review of 2021/2022 goals
3. Continued discussion of PoI Use Cases
4. Discussion of any Open Github Issues
5. Other Business/Next Steps

## Discussion

Holli - engaging with Scott Simmons to get OGC organisation wide promotion of the PoI for the Members Meeting
- Need 2 big hooks to bring people in - emailed to Scott.
-- Holli to grab some use cases from github issues and craft an email for Scott to then promote to the Members ahead of the December Members Meeting.
- We should create a "rolling" action items list/ledger in a common location that members of the SWG can refer to and do work on as the opportunity/need arises - perhaps as a persistent issue in this GitHub that has an action items table which is updated as work progresses. (Matt) will create an initial version for consideration and approval (or otherwise) of the SWG membership.

Chuck - We should approach data encodings of PoI from the application of the conceptual model 
- need to get the conceptual model out as the PoI Standard.
- Data encodings could then be extensions of either PoI or other relevant standards - e.g. cityGML/cityJSON
- (Matt) We should engage with these working groups to progress this idea

Koen - potential issue with current charter and what we are proposing to produce in the PoI 
- We may need to recharter to reflect the shift away from purely an encoding standard to a conceptual model standard.

Meeting Closed 00:10 AEST
<hr><hr>
</div>

**Comment by timoruohomaki** [comment]
Sorry wasn't able to attend, but here's a comment from the CityGML group:
"(We) would highly appreciate it, if the SWG would also consider that the location and semantics of a POI can also be just a link to an external geographic feature, e.g. in a CityGML or IFC dataset or any other geographic dataset having globally unique and stable identifiers. Such a link could also be expressed using a REST-based call to an OGC Feature API, but also using a http-get call to an OGC Web Feature Service."

**Comment by kijouneli** [comment]
Sorry that I was also not able to attend this meeting due to a conflicting schedule. As any draft or model will be available, we will try to make an extension of Indoor POI model from IndoorGML group as a PoI use case.
