### ISSUE TITLE
Unbounded Temporal Properties

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/poi#60]
Verify that the re-used temporal classes can support unbounded extents.

**Comment by cmheazel** [comment]
The temporal classes currently used in the model do not define periods, only instances. If there is a need for temporal periods, then we will have to bring in additional classes.

**Comment by dr-shorthair** [comment]
Don't forget https://www.w3.org/TR/owl-time/ and the extensions https://www.w3.org/TR/vocab-owl-time-rel/ and https://www.w3.org/TR/vocab-owl-time-agg/ 
While you may not be working in the RDF/OWL idiom, the theory and terminology here may be useful.

**Comment by geofizzydrink** [comment]
Closing issue - unbounded temporal attributes are already catered for well by the existing temporal standards that the POI data model is leveraging.
