### ISSUE TITLE
Syles/Symbology considerations for Data Model

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#61]
We need to consider the appropriate inclusion and definition of symbology/styles in the POI data model and spec.

- Joetta Krekk
- link between feature model of a POI and a reference to a symbology so any system can interpret
- 2 fields
    - 1 field to reference the symbology  - precalculated with portrails/symbologies so client system can know what to do when it sees that field (either present or populated in POI data package). Reference to symbol - not the symbol itself.
    - 1 field as a label field - precalculated and stored in a designated field to avoid unnecessary repeated queries/union opporations when client system is interogating the POI

**Comment by cmheazel** [comment]
We have included a link to symbology information but I don't think it's within our scope to define that information.

Recommend to close.

**Comment by geofizzydrink** [comment]
Issue Closed
