### ISSUE TITLE
Should a POI be called a "POI"?

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#62]
**Question posed by Jean-Christophe Malapert**

**_As I understand it, not only points but also lines and polygons are processed. In fact, the standard should be called ROI (Region of Interest), shouldn't it ?_**

---------------------------------------------------

This question has been discussed during the POI SWG Telecon on 30 June 2022.

**Comment by geofizzydrink** [comment]
We have already discussed this - i.e. feature model used the geometry to specify the coordinate reference system used by the implementer. This is technically correct, given that not all features of interest (and by extension POIs) are points. They can also be LineStrings and Polygons. While technically correct there is the inertia of existing systems that make it difficult/inappropriate to split a POI Feature. So by convention, given that POI has already been designed and implemented, we should still refer to it as a "Point" of Interest instead of say "Region of Interest"

**Comment by ReesePlews** [comment]
hi @geofizzydrink great topic for discussion! i was kinda curious about this too when i asked @cmheazel during the recent POI seminar. i am sure ROI will generate a lot of search engine hits... for something else... but it is a very good discussion topic. i am looking forward to the replies...
