### ISSUE TITLE
Do POIs support all registered/defined CRSs?

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#64]
**Question posed by Jean-Christophe Malapert**

**_I would like you to confirm that all the non-projected CRS (even extraterrestrial) are taken into account as long as they are published under http://www.opengis.net/def/crs/ ?_**

---------------------------------------------------

This question has been discussed during the POI SWG Telecon on 30 June 2022.

**Comment by cmheazel** [comment]
"All" is a dangerous word.  Easy to use, very hard to prove.

POI uses the Point, Line, and Polygon geometries defined in ISO 19107.  As such, a POI should provide the same CRS support as any other Feature. Of course, if I were to publish a CRS with a single axis, you may have trouble with your polygons.
