### ISSUE TITLE
Can POIs be clustered/aggregated in a hierarchy?

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#65]
**Question posed by Jean-Christophe Malapert**

**_At the application level, I sometimes work with millions of POIs: some of them represent a catalog of stars (https://axel.cds.unistra.fr/HiPSCatService/I/337/gaia) or craters, or even the rights-of-way of observations. In order to display all the information, they have to be clustered. For the moment, the clusters are made according to pyramidal indexes where the provider chooses a sorting in the parameters. For example, for Gaia, we display the brightest data at the top of the pyramid, and as we go down the pyramid, we display the less bright data. In parallel, we are grouping information using collections of collections.

What I see with the POI standard is that you could also cluster the POI via relations without loading a whole document, right ?_**

---------------------------------------------------

This question has been discussed during the POI SWG Telecon on 30 June 2022.

**Comment by cmheazel** [comment]
A POI is a Feature. A Feature can be either a single entity, a Collection of Features, a Collection of Feature Collections, or a mix of the above. So yes, if you can do it with a Feature you can do it with a POI.
