### ISSUE TITLE
Can the POI standard support both geometry and time descriptions in an normalised and optimal way?

### ISSUE THREAD

**Issue by geofizzydrink** [opengeospatial/poi#67]
**Question posed by Jean-Christophe Malapert**

**_I think that geometry alone is not self-sufficient. It would be nice to normalize the time in an optional way._**

---------------------------------------------------

This question has been discussed during the POI SWG Telecon on 30 June 2022.

**Comment by geofizzydrink** [comment]
We should include examples of POIs with differing temporal/spatial relationships in the Users Guide

**Comment by cmheazel** [comment]
Recommend to close.

**Comment by geofizzydrink** [comment]
issue closed
