### ISSUE TITLE
Wrong standard code RFC4087

### ISSUE THREAD

**Issue by kunlinyu** [opengeospatial/poi#71]
RFC4087 is not correct. The correct standard is RFC4287.
I raise a pull request 1 month ago.

https://github.com/opengeospatial/poi/pull/69

When I uploaded, it can be merged.
But now there are merge conflicts.

If I fix the merge conflicts, can we merge it?

**Comment by cmheazel** [comment]
Neither RFC 4087 nor RFC 4287 are referenced in the current version of the standard. The text modified by the pull request was removed in a previous update.
