### ISSUE TITLE
Is Model's use of POIProperty too cumbersome or even proper?

### ISSUE THREAD

**Issue by howardtrickey** [opengeospatial/poi#75]
The draft standard, section 6.2 (Class Model), has in Figure 5 ({POI UML Model) the following:

AbstractPOI - - - <<use>> - - -  +hasProperty (0..*) -> PoiProperty ------> GeneralFeatureModel::AttributeFeatureType

It appears that to use this, for example in JSON, one has to repeat a lot of what should be meta-information in every instance of a property. E.g.

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      45.1491802,
      -94.69078971
    ]
  },
  "properties": {
    "featureId": 693842,
    "name": {
      "name": "Bob’s Quickstop"
    },
    "contactInfo": {
      "role": "POI Provider"
    },
    "hasFeatureOfInterest": {
      "href": ""
    },
    "hasProperty": {
      "cardinality": "1",
      "valueDomain": "string",
      "valueType": "Category",
      "definition": "",
      "value": { "category" : "Convenience Store" }
    }
  }
}

I guess it is nice that the property value is self-describing, but it is very cumbersome to have to repeat the cardinality, valueDomain, and valueType in every instance. Is this what was intended in our model?

Reading ISO 19109:2015, it seems to me that things like PropertyType and its subclass Attribute were intended to be metaclasses that could be used to describe a particular feature class, but not intended to be used as actual members of a feature class the way we are doing in our POI model.  But I could be wrong, this is very new material to me.

**Comment by cmheazel** [comment]
Our problem is that POI must be able to adapt to the data model of the Features it describes. So properties have to be self-describing. That being said, this is a (platform independent) conceptual model. It cannot make assumptions about the underlying technology. Which limits our options quite a bit. Thus we end up with a somewhat cumbersome approach.

Platform specific Implementation Specifications will be generated from this platform independent model. Those standards will be able to take advantage of the tools provided by their platform technology. In the case of JSON, you could capture much of this information in a JSON schema. Each data set would have it's own POI JSON schema. If those schema are conformant with the (hypothetical) POI JSON Implementation Specification, then they will all represent the conceptual POI Property the same way.

**Comment by cperey** [comment]
Howard's question about this response: 
I see how I would write a schema to represent these properties (that I would like to have). The schema in our example is missing schema for categories. I presented an example that JSON schema allows "crap" (very loose) doesn't seem very satisfactory. 

So choices are: 
- write a different schema that defines different properties
- or?? 

Does the new schema need to be transported along with any POI file? Say, send a POI set and this would specify the extension of the model. 

Chuck's response:
The schema is referenced from the file. If you need the schema, you can go get it.  Once you have it for that source of data it will tell you a lot about the syntax. That's how all this self-describing data stuff works. 

You may (or will) have to have a schema for a data set. We could write a schema that says what different fields are but the question is do we have sufficient detail in the conceptual model or do we need to go down deeper?

Maybe need to assign an integer property, a string property and assign semantics to that property.

**Comment by cperey** [comment]
Howard's question: 
 Are we proposing that everyone who has a dataset will need to write their own schema? 
 
 Chuck: 
Consider GML, it doesn't define a schema. It is a data model.

**Comment by cperey** [comment]
Howard's preference: 
- include some common property types in the standard

It's a trade - off (understand the pros and cons). 

Chuck: 
there's also 11195 (ISO?) data types
It's up to the SWG to tell me what needs to go in there. 

The idea is to have consistency, and allow specialization (child classes of the property)

Let's take date/time interval. There are standard ways to express these. We could pull those and put them in the model as properties. 
POI Date/time, POI interval   ISO 19108
What I would like to keep in all of these is a definition attribute. It allows you to tie to an ontology. It is a powerful tool for those who want to use ontologies. 

Howard: This is a good discussion and the best way to continue is to try to write some user guide material that we can all look over and decide if we like.

**Comment by cmheazel** [comment]
POIProperty no longer exists.  We have taken a different approach.  Recommend to close.

**Comment by geofizzydrink** [comment]
Issue Closed
