### ISSUE TITLE
Revise text (explain differently to remove "latter capability")

### ISSUE THREAD

**Issue by cperey** [opengeospatial/poi#89]
Please consider this rewrite for the third paragraph:

POI-CM is a common semantic information model for the representation of POI objects that can be shared across a wide across many use cases. The ability for a POI using this conceptual model to be shared and reused is especially important with respect to the cost-effective sustainable maintenance of POI set models, allowing the possibility of selling the same data to customers from different application fields.

**Comment by geofizzydrink** [comment]
Some minor revisions from the group

POI-CM is a common semantic information model for the representation of POI objects that can be shared across many use cases. The ability for a POI using this conceptual model to be shared and reused is especially important with respect to the cost-effective sustainable maintenance of POI set models, allowing the possibility of selling the same data to customers from different application fields.

@cperey Can you please edit the introduction section and submit this as a pull request?

Cheers,
Matt.

**Comment by cmheazel** [comment]
Changes have been applied
