### ISSUE TITLE
Provide an example using the terminology and concepts introduced in the Introduction section

### ISSUE THREAD

**Issue by cperey** [opengeospatial/poi#90]
For those who might be new to the terms and concepts, they may find it useful to have a small example to illustrate their use.

The clause to be updated is [here](https://github.com/opengeospatial/poi/blob/main/22-053/sections/01-introduction.adoc).

**Comment by geofizzydrink** [comment]
@kodebaets will work up this use case scenario and an initial description of how one could create and link a POI to a far more detailed feature - i.e. POI is a summary view/access point to the underlying data.
