### ISSUE TITLE
Insert links to the specifications cited in Introduction (as footer or bibliography)

### ISSUE THREAD

**Issue by cperey** [opengeospatial/poi#91]
[The Introduction](https://github.com/opengeospatial/poi/blob/main/22-053/sections/01-introduction.adoc) contains references to many valuable references. These should be easy for the user to get to and explore. 

Please insert links or other pointers (as footer or in bibliography)

**Comment by cmheazel** [comment]
Change applied.  Currently in Normative References.  May move some of them at a latter date.
