### ISSUE TITLE
Add to the Scope section that the User Guide includes more than just explaining POI-CM

### ISSUE THREAD

**Issue by cperey** [opengeospatial/poi#92]
This guide also includes explanations for getting started (step-by-step) and an FAQ. 

There are recommendations for how to deal with non-standardized attributes.

**Comment by cmheazel** [comment]
The text reads "provides Engineering Guidance on the use of the POI Conceptual Model Standard".  That covers a lot of ground including FAQs, Getting Started, and non-Standard Attributes.

I prefer to keep a scope statement short and to the point.  Otherwise folks read too much into it.
